import type { Metadata } from "next";
import { Geist, Geist_Mono, Patrick_Hand, Dokdo, Homemade_Apple, Knewave, Mystery_Quest, Kirang_Haerang, Shadows_Into_Light, Poiret_One, Red_Hat_Display } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const patrick = Patrick_Hand({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-patrick",
})
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const apple = Dokdo({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-apple",
})
const poiret = Poiret_One({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-poiret",
})
const redhat = Red_Hat_Display({
  subsets: ["latin"],
  weight: ["400", "300", "500", "600", "800", "900"],
  variable: "--font-redhat",
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${patrick.variable} ${apple.variable} ${poiret.variable} ${redhat.variable} antialiased`}
      >
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
